### ISSUE TITLE
Could not find a declaration file for the module

### ISSUE THREAD

**Issue by TotomInc** [sumcumo/vue-history#28]
I'm trying to use the module in my Vue Typescript project but I can't have typings for the module (and it generates an error on my build):

```
Could not find a declaration file for module '@sum.cumo/vue-history'. '/Users/totominc/Desktop/Git/skid-inc/node_modules/@sum.cumo/vue-history/dist/vue-history.umd.js' implicitly has an 'any' type.
  Try `npm install @types/sum.cumo__vue-history` if it exists or add a new declaration (.d.ts) file containing `declare module '@sum.cumo/vue-history';`ts(7016)
```

When digging in the module on the `node_modules` folder, I see it packaged the `.d.ts` files but there is a mistake in the `package.json`:

```
"typings": "dist/ems/index.d.ts"
// instead of
"types": "dist/esm/index.d.ts"
```

However, this have been corrected in the actual state of the repo, maybe the fix haven't been published on npm?

**Comment by JohannesLamberts** [comment]
@TotomInc thanks for the issue. The fix has just been released (https://www.npmjs.com/package/@sum.cumo/vue-history/v/1.0.3). 
Same bug has been fixed in Vue States as well, and Vue States now also provides extended typescript support (https://www.npmjs.com/package/@sum.cumo/vue-states/v/1.1.0))
